#!/bin/sh

# Assume mpicc has been installed

CXX=mpicxx CC=mpicc cmake -H. -Bbuild -DLUA_USE_READLINE=Off -DLUA_USE_CURSES=Off -DHIVE_BUILD_WITH_MPI=On -DHIVE_BUILD_WITH_OPENMP=On -DHIVE_BUILD_WITH_CDMLIB=On -DHIVE_BUILD_WITH_HDMLIB=On -DHIVE_BUILD_WITH_PDMLIB=On -DBUILD_SHARED_LIBS=On -DHIVE_BUILD_WITH_OPENGL=Off
