#!/bin/sh

CMAKE_K=/opt/local/bin/cmake
CMAKE_FX10=/usr/local/bin/cmake
if [ -f $CMAKE_K ]; then
  CMAKE_BIN=$CMAKE_K
else
  CMAKE_BIN=$CMAKE_FX10
fi

CXX=mpiFCCpx CC=mpifccpx $CMAKE_BIN -H. -Bbuild -DHIVE_BUILD_K_CROSS_COMPILE=On -DHIVE_BUILD_WITH_MPI=On -DHIVE_BUILD_WITH_CDMLIB=On -DHIVE_BUILD_WITH_HDMLIB=On -DHIVE_BUILD_WITH_PDMLIB=On -DHIVE_BUILD_WITH_UDMLIB=On -DHIVE_BUILD_WITH_COMPOSITOR=On -DBUILD_SHARED_LIBS=Off
